version: "3.2"

services:
  site:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental --force_polling
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: ./
        target: /srv/jekyll
networks:
  default:
    driver: bridge
